name: rudify_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_tts: ^0.2.4
  audioplayers: ^0.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/voice1/armpit.mp3
    - assets/voice1/banana.mp3
    - assets/voice1/bog.mp3
    - assets/voice1/boob.mp3
    - assets/voice1/bunion.mp3
    - assets/voice1/butt.mp3
    - assets/voice1/clod.mp3
    - assets/voice1/cucumber.mp3
    - assets/voice1/desert.mp3
    - assets/voice1/dribble.mp3
    - assets/voice1/dungeon.mp3
    - assets/voice1/field.mp3
    - assets/voice1/forest.mp3
    - assets/voice1/fridge.mp3
    - assets/voice1/fudge.mp3
    - assets/voice1/furry.mp3
    - assets/voice1/garbage.mp3
    - assets/voice1/gutter.mp3
    - assets/voice1/hairy.mp3
    - assets/voice1/hedge.mp3
    - assets/voice1/hobbit.mp3
    - assets/voice1/itching.mp3
    - assets/voice1/lake.mp3
    - assets/voice1/mouldy.mp3
    - assets/voice1/mud.mp3
    - assets/voice1/muddy.mp3
    - assets/voice1/ocean.mp3
    - assets/voice1/pant.mp3
    - assets/voice1/plop.mp3
    - assets/voice1/river.mp3
    - assets/voice1/rotten.mp3
    - assets/voice1/scaly.mp3
    - assets/voice1/scratching.mp3
    - assets/voice1/sea.mp3
    - assets/voice1/slime.mp3
    - assets/voice1/slimy.mp3
    - assets/voice1/slug.mp3
    - assets/voice1/smell.mp3
    - assets/voice1/smelly.mp3
    - assets/voice1/space.mp3
    - assets/voice1/spiny.mp3
    - assets/voice1/squelchy.mp3
    - assets/voice1/squishy.mp3
    - assets/voice1/stink.mp3
    - assets/voice1/stinky.mp3
    - assets/voice1/suburban.mp3
    - assets/voice1/toe.mp3
    - assets/voice1/toenail.mp3
    - assets/voice1/toilet.mp3
    - assets/voice1/tree.mp3
    - assets/voice1/turd.mp3
    - assets/voice1/tussock.mp3
    - assets/voice1/urban.mp3
    - assets/voice1/wandering.mp3
    - assets/voice1/wood.mp3
    - assets/voice1/worm.mp3
    - assets/voice1/yourea.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
