name: rudify_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_tts: ^0.2.4
  audioplayers: ^0.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/bot.png
    - assets/icons/boy.png
    - assets/voice1/armpit.mp3
    - assets/voice1/attic.mp3
    - assets/voice1/banana.mp3
    - assets/voice1/bog.mp3
    - assets/voice1/bogey.mp3
    - assets/voice1/boob.mp3
    - assets/voice1/boring.mp3
    - assets/voice1/bulging.mp3
    - assets/voice1/bunion.mp3
    - assets/voice1/burp.mp3
    - assets/voice1/bushy.mp3
    - assets/voice1/butt.mp3
    - assets/voice1/buttock.mp3
    - assets/voice1/cave.mp3
    - assets/voice1/cellar.mp3
    - assets/voice1/cheese.mp3
    - assets/voice1/cheesy.mp3
    - assets/voice1/chimney.mp3
    - assets/voice1/cist.mp3
    - assets/voice1/clod.mp3
    - assets/voice1/cucumber.mp3
    - assets/voice1/desert.mp3
    - assets/voice1/disgusting.mp3
    - assets/voice1/dribble.mp3
    - assets/voice1/drip.mp3
    - assets/voice1/dripping.mp3
    - assets/voice1/dungeon.mp3
    - assets/voice1/faded.mp3
    - assets/voice1/fart.mp3
    - assets/voice1/field.mp3
    - assets/voice1/flump.mp3
    - assets/voice1/forest.mp3
    - assets/voice1/fridge.mp3
    - assets/voice1/fudge.mp3
    - assets/voice1/furry.mp3
    - assets/voice1/garbage.mp3
    - assets/voice1/gassy.mp3
    - assets/voice1/gelatinous.mp3
    - assets/voice1/greasy.mp3
    - assets/voice1/gutter.mp3
    - assets/voice1/hairy.mp3
    - assets/voice1/hedge.mp3
    - assets/voice1/hobbit.mp3
    - assets/voice1/hole.mp3
    - assets/voice1/itching.mp3
    - assets/voice1/lake.mp3
    - assets/voice1/log.mp3
    - assets/voice1/lump.mp3
    - assets/voice1/marsh.mp3
    - assets/voice1/mould.mp3
    - assets/voice1/mouldy.mp3
    - assets/voice1/mud.mp3
    - assets/voice1/muddy.mp3
    - assets/voice1/nostrill.mp3
    - assets/voice1/nugget.mp3
    - assets/voice1/ocean.mp3
    - assets/voice1/oily.mp3
    - assets/voice1/oozing.mp3
    - assets/voice1/orange.mp3
    - assets/voice1/orifice.mp3
    - assets/voice1/ouzing.mp3
    - assets/voice1/pant.mp3
    - assets/voice1/plop.mp3
    - assets/voice1/plug.mp3
    - assets/voice1/rancid.mp3
    - assets/voice1/raspberry.mp3
    - assets/voice1/river.mp3
    - assets/voice1/rotten.mp3
    - assets/voice1/scab.mp3
    - assets/voice1/scabby.mp3
    - assets/voice1/scaly.mp3
    - assets/voice1/scratching.mp3
    - assets/voice1/sea.mp3
    - assets/voice1/sewer.mp3
    - assets/voice1/slime.mp3
    - assets/voice1/slimy.mp3
    - assets/voice1/slug.mp3
    - assets/voice1/smell.mp3
    - assets/voice1/smelly.mp3
    - assets/voice1/soggy.mp3
    - assets/voice1/space.mp3
    - assets/voice1/spillage.mp3
    - assets/voice1/spiny.mp3
    - assets/voice1/spotty.mp3
    - assets/voice1/squeaky.mp3
    - assets/voice1/squelchy.mp3
    - assets/voice1/squishy.mp3
    - assets/voice1/stain.mp3
    - assets/voice1/stench.mp3
    - assets/voice1/stink.mp3
    - assets/voice1/stinky.mp3
    - assets/voice1/suburban.mp3
    - assets/voice1/toad.mp3
    - assets/voice1/toe.mp3
    - assets/voice1/toenail.mp3
    - assets/voice1/toilet.mp3
    - assets/voice1/tree.mp3
    - assets/voice1/trumpet.mp3
    - assets/voice1/turd.mp3
    - assets/voice1/tussock.mp3
    - assets/voice1/twit.mp3
    - assets/voice1/urban.mp3
    - assets/voice1/wandering.mp3
    - assets/voice1/wart.mp3
    - assets/voice1/waxy.mp3
    - assets/voice1/wiener.mp3
    - assets/voice1/wood.mp3
    - assets/voice1/worm.mp3
    - assets/voice1/yourea.mp3
    - assets/voice2/armpit.mp3
    - assets/voice2/attic.mp3
    - assets/voice2/banana.mp3
    - assets/voice2/bog.mp3
    - assets/voice2/bogey.mp3
    - assets/voice2/boob.mp3
    - assets/voice2/boring.mp3
    - assets/voice2/bulging.mp3
    - assets/voice2/bunion.mp3
    - assets/voice2/burp.mp3
    - assets/voice2/bushy.mp3
    - assets/voice2/butt.mp3
    - assets/voice2/buttock.mp3
    - assets/voice2/cave.mp3
    - assets/voice2/cellar.mp3
    - assets/voice2/cheese.mp3
    - assets/voice2/cheesy.mp3
    - assets/voice2/chimney.mp3
    - assets/voice2/cist.mp3
    - assets/voice2/clod.mp3
    - assets/voice2/cucumber.mp3
    - assets/voice2/desert.mp3
    - assets/voice2/disgusting.mp3
    - assets/voice2/dribble.mp3
    - assets/voice2/drip.mp3
    - assets/voice2/dripping.mp3
    - assets/voice2/dungeon.mp3
    - assets/voice2/faded.mp3
    - assets/voice2/fart.mp3
    - assets/voice2/field.mp3
    - assets/voice2/flump.mp3
    - assets/voice2/forest.mp3
    - assets/voice2/fridge.mp3
    - assets/voice2/fudge.mp3
    - assets/voice2/furry.mp3
    - assets/voice2/garbage.mp3
    - assets/voice2/gassy.mp3
    - assets/voice2/gelatinous.mp3
    - assets/voice2/greasy.mp3
    - assets/voice2/gutter.mp3
    - assets/voice2/hairy.mp3
    - assets/voice2/hedge.mp3
    - assets/voice2/hobbit.mp3
    - assets/voice2/hole.mp3
    - assets/voice2/itching.mp3
    - assets/voice2/lake.mp3
    - assets/voice2/log.mp3
    - assets/voice2/lump.mp3
    - assets/voice2/marsh.mp3
    - assets/voice2/mould.mp3
    - assets/voice2/mouldy.mp3
    - assets/voice2/mud.mp3
    - assets/voice2/muddy.mp3
    - assets/voice2/nostrill.mp3
    - assets/voice2/nugget.mp3
    - assets/voice2/ocean.mp3
    - assets/voice2/oily.mp3
    - assets/voice2/oozing.mp3
    - assets/voice2/orange.mp3
    - assets/voice2/orifice.mp3
    - assets/voice2/ouzing.mp3
    - assets/voice2/pant.mp3
    - assets/voice2/plop.mp3
    - assets/voice2/plug.mp3
    - assets/voice2/rancid.mp3
    - assets/voice2/raspberry.mp3
    - assets/voice2/river.mp3
    - assets/voice2/rotten.mp3
    - assets/voice2/scab.mp3
    - assets/voice2/scabby.mp3
    - assets/voice2/scaly.mp3
    - assets/voice2/scratching.mp3
    - assets/voice2/sea.mp3
    - assets/voice2/sewer.mp3
    - assets/voice2/slime.mp3
    - assets/voice2/slimy.mp3
    - assets/voice2/slug.mp3
    - assets/voice2/smell.mp3
    - assets/voice2/smelly.mp3
    - assets/voice2/soggy.mp3
    - assets/voice2/space.mp3
    - assets/voice2/spillage.mp3
    - assets/voice2/spiny.mp3
    - assets/voice2/spotty.mp3
    - assets/voice2/squeaky.mp3
    - assets/voice2/squelchy.mp3
    - assets/voice2/squishy.mp3
    - assets/voice2/stain.mp3
    - assets/voice2/stench.mp3
    - assets/voice2/stink.mp3
    - assets/voice2/stinky.mp3
    - assets/voice2/suburban.mp3
    - assets/voice2/toad.mp3
    - assets/voice2/toe.mp3
    - assets/voice2/toenail.mp3
    - assets/voice2/toilet.mp3
    - assets/voice2/tree.mp3
    - assets/voice2/trumpet.mp3
    - assets/voice2/turd.mp3
    - assets/voice2/tussock.mp3
    - assets/voice2/twit.mp3
    - assets/voice2/urban.mp3
    - assets/voice2/wandering.mp3
    - assets/voice2/wart.mp3
    - assets/voice2/waxy.mp3
    - assets/voice2/wiener.mp3
    - assets/voice2/wood.mp3
    - assets/voice2/worm.mp3
    - assets/voice2/yourea.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nanum
      fonts:
        - asset: fonts/NanumPenScript-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
